### ISSUE TITLE
Default drive doesn't work

### ISSUE THREAD

**Issue by RossComputerGuy** [Nold360/mksdiso#3]
I found out that using the default drive as `/dev/cdrw` is not really good because most Linux installations now use `/dev/sr#` to access the drive.

**Comment by InklingGirl** [comment]
Bump, same issue, sad this is abandonware, but because it's F/LOSS at least any user–developer – w/ the requisite skills – has the freedom/liberty to fork & maintain it.

**Comment by Nold360** [comment]
I merged #13 hope this help with these issues

**Comment by InklingGirl** [comment]
thank you!
